name: Cloudsmith Raw File Download Test

on:
  workflow_dispatch:

env:
  RES_DIR: downloads

jobs:
  test-download:
    runs-on: ubuntu-latest

    steps:
      - name: Create download directory
        run: mkdir -p "${{ env.RES_DIR }}"

      - name: Download files from Cloudsmith
        run: |
          set -eo pipefail

          files=(
            "0_Mountains_Valley_3840x2160.mov"
            "gfsanl_4_20200101_0000_000.grb2"
          )

          for file in "${files[@]}"; do
            echo "Downloading file: ${file}"
            curl -1sLf -O "https://dl.cloudsmith.io/pErRvCX9YQ7gA6Q7/workspace-for-rajdeep/new1/raw/files/${file}" \
              --output "${RES_DIR}/${file}"
          done

      - name: List downloaded files
        run: ls -lh "${{ env.RES_DIR }}"
